#pragma once

enum render_target_index {
	RENDER_TARGET_DEFAULT,
	RENDER_TARGET_MINIMAP,
	RENDER_TARGETS_LENGTH,
};

enum texture_index {
	TEX_RENDER_RGBA,
	TEX_RENDER_NORMALS,
	TEX_RENDER_DEPTH,
	TEX_MINIMAP_RGBA,
	TEX_MINIMAP_NORMALS,
	TEX_MINIMAP_DEPTH,
	TEX_CHECKER,
	TEX_WRAPPING1,
	TEXTURES_LENGTH,
};

enum material_index {
	MAT_COLORED_UNLIT,
	MAT_TEXTURED_UNLIT,
	MAT_POSTPROCESS,
	MATERIALS_LENGTH,
};

enum mesh_index {
	MESH_CUBE,
	MESH_GIFT,
	MESH_QUAD,
	MESH_MONKEY,
	// Furniture.
	MESH_CHAIR,
	MESH_LAMP,
	MESH_SOFA,
	MESHES_LENGTH,
};
